---
- hosts: all
  become: yes
  vars_prompt: 
  - name: packname
    prompt: "enter the package name"
    private: no
  tasks:
  - name: install {{packname}} package
    package: name= {{packname}} state=installed

    
 
