- hosts: all
  become: yes
  vars: 
    packname: tomcat7
    packname1: nginx
  tasks:
  - name: tomcat installation
    package: name="{{packname}}" state=installed
  - name: starting tomcat7
    service: name="{{packname}}" state=started
  - name: nginx installation
    package: name="{{packname1}}" state=installed
  - name: starting nginx
    service: name="{{packname1}}" state=started


